# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Las < Formula
  desc "Retrieves a list of all email addresses that are on the suppression list for Amazon SES."
  homepage "https://github.com/winebarrel/las"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/las/releases/download/v0.1.0/las_0.1.0_darwin_amd64.tar.gz"
      sha256 "b0debda060aa8b35b56d93e94a4714f81b2f094de745a63df703388c53101b3a"

      def install
        bin.install 'las'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/las/releases/download/v0.1.0/las_0.1.0_darwin_arm64.tar.gz"
      sha256 "d511471b74cea3e067767cc2423adc3d326c434a4fb155780208c0c19d539335"

      def install
        bin.install 'las'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/las/releases/download/v0.1.0/las_0.1.0_linux_amd64.tar.gz"
      sha256 "746c4014ce0531b447055dd9c28466a723896eba0b5477ccfa884db7b170af77"

      def install
        bin.install 'las'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/las/releases/download/v0.1.0/las_0.1.0_linux_arm64.tar.gz"
      sha256 "a5e262d09205898d27714c0e642c058a85a4ce1043eb207ca98d20ec3b5d195e"

      def install
        bin.install 'las'
      end
    end
  end
end
